// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'model/entity_todo.dart';
import 'model/entity_user.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 1147383777137200332),
    name: 'EntityTodo',
    lastPropertyId: const obx_int.IdUid(3, 1867743761346138964),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 3348683640685915239),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 7249032541124978553),
        name: 'title',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 1867743761346138964),
        name: 'done',
        type: 1,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(4, 5104349737090255391),
    name: 'EntityUser',
    lastPropertyId: const obx_int.IdUid(31, 9181542147081844573),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 1495181100193013884),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 1504858958319760505),
        name: 'first',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 6552955021699084261),
        name: 'last',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 6518005691905055922),
        name: 'password',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 3481175608400362010),
        name: 'role',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(16, 898555668029515205),
        name: 'username',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(17, 3036020623274304158),
        name: 'mongoId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(18, 4177830031326948127),
        name: 'storeId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(19, 2992761431304668351),
        name: 'isActive',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(20, 5801911642910539262),
        name: 'permissions',
        type: 30,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(21, 7977904979280424757),
        name: 'lastLoginAt',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(22, 1182801360356253480),
        name: 'lastLoginDevice',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(23, 7852084800764839974),
        name: 'isSync',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(24, 8321519840270371502),
        name: 'dob',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(25, 2282861970650858076),
        name: 'gender',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(26, 2562536171618553518),
        name: 'lastLoginIp',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(27, 9092976365591404161),
        name: 'mobileNumber',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(28, 297220764132768482),
        name: 'alternateMobile',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(29, 7714058559799491755),
        name: 'idProofType',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(30, 4832728562901764663),
        name: 'idProofNumber',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(31, 9181542147081844573),
        name: 'address',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(6, 9896093361547320),
    lastIndexId: const obx_int.IdUid(2, 788824281217006709),
    lastRelationId: const obx_int.IdUid(1, 6501938934487787319),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [
      2068234702357059179,
      3454218793974297374,
      3178511261096980415,
      9896093361547320,
    ],
    retiredIndexUids: const [788824281217006709],
    retiredPropertyUids: const [
      3516755657228606734,
      8803490122477689604,
      2944430541412780171,
      3309115737670219444,
      5223182377567394073,
      5574173884827893879,
      6748390824982335381,
      4859619953360379597,
      5671324819876027021,
      6396553978326563655,
      20024624344831898,
      7590925265900710385,
      734334106254997583,
      8018654486292578026,
      2049831581028923053,
      1299140852094662050,
      647700186519365683,
      6029204616208454494,
      2387368428240739454,
      302509615983465650,
      4128503591430391527,
      774549012799115341,
      6149963335864363990,
      4610397219393176656,
      8472664274620694792,
      1254419653813628934,
      8466130324932066093,
      713413285719264143,
      4440776724028837419,
      895153431473126844,
      1580069916921015543,
      4452634026319547425,
      9047017747620241200,
    ],
    retiredRelationUids: const [6501938934487787319],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    EntityTodo: obx_int.EntityDefinition<EntityTodo>(
      model: _entities[0],
      toOneRelations: (EntityTodo object) => [],
      toManyRelations: (EntityTodo object) => {},
      getId: (EntityTodo object) => object.id,
      setId: (EntityTodo object, int id) {
        object.id = id;
      },
      objectToFB: (EntityTodo object, fb.Builder fbb) {
        final titleOffset = fbb.writeString(object.title);
        fbb.startTable(4);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, titleOffset);
        fbb.addBool(2, object.done);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final titleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final doneParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          8,
          false,
        );
        final object = EntityTodo(
          id: idParam,
          title: titleParam,
          done: doneParam,
        );

        return object;
      },
    ),
    EntityUser: obx_int.EntityDefinition<EntityUser>(
      model: _entities[1],
      toOneRelations: (EntityUser object) => [],
      toManyRelations: (EntityUser object) => {},
      getId: (EntityUser object) => object.id,
      setId: (EntityUser object, int id) {
        object.id = id;
      },
      objectToFB: (EntityUser object, fb.Builder fbb) {
        final firstOffset = object.first == null
            ? null
            : fbb.writeString(object.first!);
        final lastOffset = object.last == null
            ? null
            : fbb.writeString(object.last!);
        final passwordOffset = object.password == null
            ? null
            : fbb.writeString(object.password!);
        final roleOffset = object.role == null
            ? null
            : fbb.writeString(object.role!);
        final usernameOffset = object.username == null
            ? null
            : fbb.writeString(object.username!);
        final mongoIdOffset = object.mongoId == null
            ? null
            : fbb.writeString(object.mongoId!);
        final storeIdOffset = object.storeId == null
            ? null
            : fbb.writeString(object.storeId!);
        final permissionsOffset = object.permissions == null
            ? null
            : fbb.writeList(
                object.permissions!
                    .map(fbb.writeString)
                    .toList(growable: false),
              );
        final lastLoginAtOffset = object.lastLoginAt == null
            ? null
            : fbb.writeString(object.lastLoginAt!);
        final lastLoginDeviceOffset = object.lastLoginDevice == null
            ? null
            : fbb.writeString(object.lastLoginDevice!);
        final dobOffset = object.dob == null
            ? null
            : fbb.writeString(object.dob!);
        final genderOffset = object.gender == null
            ? null
            : fbb.writeString(object.gender!);
        final lastLoginIpOffset = object.lastLoginIp == null
            ? null
            : fbb.writeString(object.lastLoginIp!);
        final mobileNumberOffset = object.mobileNumber == null
            ? null
            : fbb.writeString(object.mobileNumber!);
        final alternateMobileOffset = object.alternateMobile == null
            ? null
            : fbb.writeString(object.alternateMobile!);
        final idProofTypeOffset = object.idProofType == null
            ? null
            : fbb.writeString(object.idProofType!);
        final idProofNumberOffset = object.idProofNumber == null
            ? null
            : fbb.writeString(object.idProofNumber!);
        final addressOffset = object.address == null
            ? null
            : fbb.writeString(object.address!);
        fbb.startTable(32);
        fbb.addInt64(0, object.id);
        fbb.addOffset(3, firstOffset);
        fbb.addOffset(5, lastOffset);
        fbb.addOffset(9, passwordOffset);
        fbb.addOffset(10, roleOffset);
        fbb.addOffset(15, usernameOffset);
        fbb.addOffset(16, mongoIdOffset);
        fbb.addOffset(17, storeIdOffset);
        fbb.addBool(18, object.isActive);
        fbb.addOffset(19, permissionsOffset);
        fbb.addOffset(20, lastLoginAtOffset);
        fbb.addOffset(21, lastLoginDeviceOffset);
        fbb.addBool(22, object.isSync);
        fbb.addOffset(23, dobOffset);
        fbb.addOffset(24, genderOffset);
        fbb.addOffset(25, lastLoginIpOffset);
        fbb.addOffset(26, mobileNumberOffset);
        fbb.addOffset(27, alternateMobileOffset);
        fbb.addOffset(28, idProofTypeOffset);
        fbb.addOffset(29, idProofNumberOffset);
        fbb.addOffset(30, addressOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final mobileNumberParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 56);
        final alternateMobileParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 58);
        final idProofNumberParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 62);
        final idProofTypeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 60);
        final addressParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 64);
        final mongoIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 36);
        final firstParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 10);
        final lastParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 14);
        final dobParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 50);
        final genderParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 52);
        final usernameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 34);
        final passwordParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 22);
        final roleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 24);
        final storeIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 38);
        final isActiveParam = const fb.BoolReader().vTableGetNullable(
          buffer,
          rootOffset,
          40,
        );
        final permissionsParam = const fb.ListReader<String>(
          fb.StringReader(asciiOptimization: true),
          lazy: false,
        ).vTableGetNullable(buffer, rootOffset, 42);
        final lastLoginAtParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 44);
        final lastLoginDeviceParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 46);
        final lastLoginIpParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 54);
        final isSyncParam = const fb.BoolReader().vTableGetNullable(
          buffer,
          rootOffset,
          48,
        );
        final object = EntityUser(
          id: idParam,
          mobileNumber: mobileNumberParam,
          alternateMobile: alternateMobileParam,
          idProofNumber: idProofNumberParam,
          idProofType: idProofTypeParam,
          address: addressParam,
          mongoId: mongoIdParam,
          first: firstParam,
          last: lastParam,
          dob: dobParam,
          gender: genderParam,
          username: usernameParam,
          password: passwordParam,
          role: roleParam,
          storeId: storeIdParam,
          isActive: isActiveParam,
          permissions: permissionsParam,
          lastLoginAt: lastLoginAtParam,
          lastLoginDevice: lastLoginDeviceParam,
          lastLoginIp: lastLoginIpParam,
          isSync: isSyncParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [EntityTodo] entity fields to define ObjectBox queries.
class EntityTodo_ {
  /// See [EntityTodo.id].
  static final id = obx.QueryIntegerProperty<EntityTodo>(
    _entities[0].properties[0],
  );

  /// See [EntityTodo.title].
  static final title = obx.QueryStringProperty<EntityTodo>(
    _entities[0].properties[1],
  );

  /// See [EntityTodo.done].
  static final done = obx.QueryBooleanProperty<EntityTodo>(
    _entities[0].properties[2],
  );
}

/// [EntityUser] entity fields to define ObjectBox queries.
class EntityUser_ {
  /// See [EntityUser.id].
  static final id = obx.QueryIntegerProperty<EntityUser>(
    _entities[1].properties[0],
  );

  /// See [EntityUser.first].
  static final first = obx.QueryStringProperty<EntityUser>(
    _entities[1].properties[1],
  );

  /// See [EntityUser.last].
  static final last = obx.QueryStringProperty<EntityUser>(
    _entities[1].properties[2],
  );

  /// See [EntityUser.password].
  static final password = obx.QueryStringProperty<EntityUser>(
    _entities[1].properties[3],
  );

  /// See [EntityUser.role].
  static final role = obx.QueryStringProperty<EntityUser>(
    _entities[1].properties[4],
  );

  /// See [EntityUser.username].
  static final username = obx.QueryStringProperty<EntityUser>(
    _entities[1].properties[5],
  );

  /// See [EntityUser.mongoId].
  static final mongoId = obx.QueryStringProperty<EntityUser>(
    _entities[1].properties[6],
  );

  /// See [EntityUser.storeId].
  static final storeId = obx.QueryStringProperty<EntityUser>(
    _entities[1].properties[7],
  );

  /// See [EntityUser.isActive].
  static final isActive = obx.QueryBooleanProperty<EntityUser>(
    _entities[1].properties[8],
  );

  /// See [EntityUser.permissions].
  static final permissions = obx.QueryStringVectorProperty<EntityUser>(
    _entities[1].properties[9],
  );

  /// See [EntityUser.lastLoginAt].
  static final lastLoginAt = obx.QueryStringProperty<EntityUser>(
    _entities[1].properties[10],
  );

  /// See [EntityUser.lastLoginDevice].
  static final lastLoginDevice = obx.QueryStringProperty<EntityUser>(
    _entities[1].properties[11],
  );

  /// See [EntityUser.isSync].
  static final isSync = obx.QueryBooleanProperty<EntityUser>(
    _entities[1].properties[12],
  );

  /// See [EntityUser.dob].
  static final dob = obx.QueryStringProperty<EntityUser>(
    _entities[1].properties[13],
  );

  /// See [EntityUser.gender].
  static final gender = obx.QueryStringProperty<EntityUser>(
    _entities[1].properties[14],
  );

  /// See [EntityUser.lastLoginIp].
  static final lastLoginIp = obx.QueryStringProperty<EntityUser>(
    _entities[1].properties[15],
  );

  /// See [EntityUser.mobileNumber].
  static final mobileNumber = obx.QueryStringProperty<EntityUser>(
    _entities[1].properties[16],
  );

  /// See [EntityUser.alternateMobile].
  static final alternateMobile = obx.QueryStringProperty<EntityUser>(
    _entities[1].properties[17],
  );

  /// See [EntityUser.idProofType].
  static final idProofType = obx.QueryStringProperty<EntityUser>(
    _entities[1].properties[18],
  );

  /// See [EntityUser.idProofNumber].
  static final idProofNumber = obx.QueryStringProperty<EntityUser>(
    _entities[1].properties[19],
  );

  /// See [EntityUser.address].
  static final address = obx.QueryStringProperty<EntityUser>(
    _entities[1].properties[20],
  );
}
